# Configura o Spring para usar o banco H2 em memória
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Libera o console do H2 (navegador)
spring.h2.console.enabled=true

# Seguranca e JWT
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ignora erros de mapeamento de tipos no Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true

server.port=${PORT:8080}